export default function ChessDatabaseSection() {
  return (
    <div className="chess-page-opening-moves">
      <h1>200,000+</h1>
      <div className="h3 text-center">Opening moves in the database</div>

      <div className="h5 chess-page-opening-moves-description">
        The database was generated by playing my chess AI against Stockfish
        (world's strongest chess ai) and recording the moves played to a certain
        depth. If the position was good, the move was kept in the database. This
        was done for every possible starting move.
      </div>
    </div>
  );
}
